memory_limit=512M
upload_max_filesize=128M
post_max_size=128M
max_execution_time=240
max_input_time=60
display_errors=
error_reporting=22519
default_charset=UTF-8
file_uploads=1
allow_url_fopen=1
date.timezone=UTC
